'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    'nav.home': '首頁',
    'nav.database': '資料庫',
    'nav.about': '關於我們',
    'nav.blog': '生態誌',
    'nav.contact': '聯絡我們',
    'hero.badge': '自然匯誌',
    'hero.title': '香港生物多樣性',
    'hero.subtitle_part1': '探索香港超過 ',
    'hero.subtitle_part2': '10,000',
    'hero.subtitle_part3': ' 種物種的詳盡資料庫，展現本地生態系統的驚人豐富度。',
    'search.placeholder': '快速搜尋俗名、學名...',
    'search.sidebar_placeholder': '快速搜尋...',
    'filter.title': '物種篩選',
    'filter.taxonomy': '物種分類層級',
    'filter.rarity': '瀕危等級與現狀',
    'filter.reset': '重置',
    'filter.clear_all': '清除所有篩選',
    'results.found': '找到',
    'results.unit': '項結果',
    'results.viewing_page': '正在查看第',
    'results.page_of': '頁，共',
    'sort.label': '排序方式',
    'sort.common_name': '俗名 (A-Z)',
    'sort.scientific_name': '學名 (A-Z)',
    'sort.rarity': '瀕危等級 (高級優先)',
    'pagination.page': '頁',
    'pagination.showing': '顯示',
    'pagination.of': '之中的',
    'pagination.species': '個物種',
    'empty.title': '找不到匹配的物種',
    'empty.subtitle': '請嘗試放寬篩選條件，或使用不同的搜尋字串進行檢索。',
    'view.per_page': '每頁顯示',
    'auth.login': '登入',
    'auth.logout': '登出',
    'view.display_mode': '顯示模式',
    'view.mode_detail': '詳情模式',
    'view.mode_photo': '照片模式',
    'view.mode_table': '表格模式',
    'table.order': '目',
    'table.family': '科',
    'table.genus': '屬',
    'table.scientific_name': '科學名',
    'table.common_name': '俗名',
    'table.native_status': '原生狀態',
    'table.iucn_status': 'IUCN 狀態',
    // 會員面板
    'account.title': '帳號設定',
    'account.tab_profile': '個人資料',
    'account.tab_bookmarks': '我的收藏',
    'account.member_since': '加入日期',
    'account.last_online': '最後上線時間',
     'account.email': '電子信箱',
    'account.role': '使用者權限',
    'account.role_admin': '管理員',
    'account.role_curator': '策展人',
    'account.role_guest': '訪客',
    'account.username': '使用者名稱',
    'account.username_placeholder': '輸入英文、數字、空格、_ 或 -',
    'account.username_hint': '支援英文字母、數字、半形空格、_ 及 -',
    'account.username_available': '此名稱可使用',
    'account.username_taken': '此名稱已被使用',
    'account.username_invalid': '僅支援英文字母、數字、空格、_ 及 -',
    'account.username_too_short': '至少需要 3 個字元',
    'account.username_checking': '檢查中...',
    'account.save': '儲存變更',
    'account.saving': '儲存中...',
    'account.save_success': '已成功更新！',
    'account.save_error': '儲存失敗，請稍後再試',
    'account.back': '返回首頁',
    'account.not_logged_in': '請先登入以查看帳號設定',
    'account.bookmarks_empty': '您尚未收藏任何物種',
    'account.bookmarks_empty_hint': '在物種卡片上點擊心形圖示即可收藏',
    'account.remove_bookmark': '移除收藏',
    'account.header_link': '帳號設定',
    'account.profile_info': '帳號資訊',
    'account.inat_info': 'iNaturalist 整合',
    'account.inat_username': 'iNaturalist 帳號名稱',
    'account.inat_username_placeholder': '輸入您的 iNaturalist 使用者名稱',
    'account.inat_usage_consent': '我同意讓本網站取用我標示為 "All Rights Reserved" 的照片',
    'account.inat_usage_hint': '勾選後，當物種圖庫、卡片或縮圖顯示您的 iNaturalist 照片時，即使您在 iNaturalist 設定為版權所有，本網站也能為您顯示該圖片。',
    'nav.privacy': '隱私權政策',
    'nav.terms': '服務條款',
    'footer.resources': '資源中心',
    'footer.community': '加入社群',
    'footer.legal': '法律資訊',
    'footer.mission': 'HKBC 致力於記錄與保護香港豐富的生物多樣性，為公眾、研究者與決策者提供權威的自然數據。',
    'footer.contribution': '參與貢獻',
    'footer.inat_link': 'iNaturalist 香港專案',
    'footer.all_rights': '版權所有 © 2024 香港自然生態匯誌 (HKBC)',
    'loading.message': '正在從雲端載入物種資料...',
    'loading.searching': '正在檢索自然數據庫，請稍候...',
    'dropdown.reset': '重設',
    'dropdown.apply': '套用',
    'dropdown.apply_selection': '確定選取',
    'dropdown.no_results': '找不到符合的分類',
    'dropdown.clear_search': '清除搜尋',
    'gallery.set_profile_error': '封面照片更新失敗',
    'gallery.set_profile_success': '設定成功',
    'gallery.current_profile': '封面圖片',
    'gallery.set_profile_picture': '設為封面圖片',
    // 管理後台
    'nav.manage': '管理',
    'admin.title': '系統管理',
    'admin.taxa_manager': '物種庫管理',
    'admin.users_manager': '用戶管理',
    'admin.last_online': '最後上線',
    'admin.joined_at': '註冊時間',
    'admin.inat_username': 'iNat 帳號',
    'admin.consent': '版權同意',
    'admin.role': '權限',
    'admin.actions': '操作',
    'admin.change_role': '修改權限',
    'admin.remove_user': '移除用戶',
    'admin.confirm_remove_title': '變更用戶狀態？',
    'admin.confirm_remove': '確定要變更此用戶的狀態嗎？被封鎖的用戶將無法存取系統。',
    'admin.status_active': '正常',
    'admin.status_blocked': '已封鎖',
    'admin.taxa_fauna': '動物分類管理',
    'admin.taxa_flora': '植物分類管理',
    'admin.species_fauna': '動物物種管理',
    'admin.species_flora': '植物物種管理',
    'admin.taxonomy_manager': '分類管理',
    'admin.taxa_group': '分類群',
    'admin.rank': '層階',
    'admin.taxa_type': '類型',
    'admin.name_eng': '英文名',
    'admin.name_chi': '中文名',
    'admin.scientific_name': '學名',
    'admin.search_taxonomy': '搜尋分類名稱...',
    'admin.species_manager': '動物物種管理',
    'admin.taxa_id': '物種 ID',
    'admin.informal_group_eng': '小分類群',
    'admin.category_eng': '類別',
    'admin.showing': '正在顯示第 {start} 至 {end} 筆，共 {total} 筆',
    'admin.total_ratio': '總計: {filtered} / {total}',
    'admin.clear_all': '清除全部',
    'admin.common_name_eng': '英文俗名',
    'admin.common_name_chi': '中文俗名',
    'admin.class_eng': '綱',
    'admin.order_eng': '目',
    'admin.family_eng': '科',
    'admin.genus_eng': '屬',
    'admin.species_eng': '種',
    'admin.status': '狀態',
    'admin.edit_hint': '點擊文字即可即時編輯',
    'common.confirm': '確認變更',
    'common.cancel': '取消',
    'admin.no_users': '找不到用戶資料',
    'admin.search_placeholder': '搜尋用戶名稱或 iNat 帳號...',
    // 首頁
    'home.slogan': '走入山林海影，留下共筆足跡。',
    'home.discover_hk': '探索香港自然',
    'home.hero_title_part1': '探索',
    'home.hero_title_part2': '生物多樣性',
    'home.hero_title_part3': '在香港',
    'home.stats_title_part1': '收錄物種',
    'home.stats_title_part2': '多樣性',
    'home.stats_desc': '目前數據庫已收錄香港超過 {total} 種物種，包含 {fauna} 種動物及 {flora} 種植物。',
    'home.total_taxa': '物種總數',
    'home.flora': '植物',
    'home.fauna': '動物',
    'home.news_announcement': '網站公告',
    'home.news_new_species': '新增物種',
    'home.view_more': '查看更多',
    'home.enter_database': '進入資料庫',
    'home.added_species': '新增物種：',
    'home.leaderboard_title': '貢獻排行榜',
    'home.top_contributors': '首要貢獻者',
    'home.score': '積分',
    'home.view_full_leaderboard': '查看完整榜單',
    'home.community_discussion': '最新社群討論',
    'home.community_feed': '社群動態',
    'home.go_to_discussion': '前往討論',
    'home.no_comments': '目前尚無評論，快來搶沙發！',
    // 分類群翻譯
    'taxa.Birds': '鳥類',
    'taxa.Butterflies': '蝴蝶',
    'taxa.Odonates': '蜻蜓與蟌',
    'taxa.Reptiles': '爬行類',
    'taxa.Amphibians': '兩棲類',
    'taxa.Fish': '魚類',
    'taxa.Mammals': '哺乳類',
    'taxa.Ants': '螞蟻',
    'taxa.Beetles': '甲蟲',
    'taxa.Plants': '植物',
    'taxa.Flora': '植物',
    'taxa.Freshwater Fish': '淡水魚',
    'taxa.Marine Fish': '海洋魚'
  },
  en: {
    'nav.home': 'Home',
    'nav.database': 'Database',
    'nav.about': 'About',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'hero.badge': 'Nature Collective',
    'hero.title': 'Hong Kong Biodiversity',
    'hero.subtitle_part1': 'Explore our comprehensive database of over ',
    'hero.subtitle_part2': '10,000',
    'hero.subtitle_part3': ' species, showcasing the incredible richness of Hong Kong\'s local ecosystems.',
    'search.placeholder': 'Search common/scientific names...',
    'search.sidebar_placeholder': 'Quick filter search...',
    'filter.title': 'Species Filter',
    'filter.taxonomy': 'Taxonomy Levels',
    'filter.rarity': 'IUCN Status & Status',
    'filter.reset': 'Reset',
    'filter.clear_all': 'Clear All Filters',
    'results.found': 'Found',
    'results.unit': 'Results',
    'results.viewing_page': 'Viewing Page',
    'results.page_of': 'of',
    'sort.label': 'Sort By',
    'sort.common_name': 'Common Name (A-Z)',
    'sort.scientific_name': 'Scientific Name (A-Z)',
    'sort.rarity': 'IUCN Status (High First)',
    'pagination.page': 'Page',
    'pagination.showing': 'Showing',
    'pagination.of': 'of',
    'pagination.species': 'Species',
    'empty.title': 'No Matching Species Found',
    'empty.subtitle': 'Try relaxing your filters or using different search terms.',
    'view.per_page': 'Per Page',
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'view.display_mode': 'Display Mode',
    'view.mode_detail': 'Detail Mode',
    'view.mode_photo': 'Photo Mode',
    'view.mode_table': 'Table Mode',
    'table.order': 'Order',
    'table.family': 'Family',
    'table.genus': 'Genus',
    'table.scientific_name': 'Scientific Name',
    'table.common_name': 'Common Name',
    'table.native_status': 'Native Status',
    'table.iucn_status': 'IUCN Status',
    // Account Panel
    'account.title': 'Account Settings',
    'account.tab_profile': 'Profile',
    'account.tab_bookmarks': 'My Bookmarks',
    'account.member_since': 'Member Since',
    'account.last_online': 'Last Online',
     'account.email': 'Email',
    'account.role': 'User Role',
    'account.role_admin': 'Admin',
    'account.role_curator': 'Curator',
    'account.role_guest': 'Guest',
    'account.username': 'Username',
    'account.username_placeholder': 'Letters, numbers, spaces, _ or -',
    'account.username_hint': 'Letters, numbers, spaces, _ and - only',
    'account.username_available': 'Username is available',
    'account.username_taken': 'Username is already taken',
    'account.username_invalid': 'Letters, numbers, spaces, _ and - only',
    'account.username_too_short': 'At least 3 characters required',
    'account.username_checking': 'Checking...',
    'account.save': 'Save Changes',
    'account.saving': 'Saving...',
    'account.save_success': 'Updated successfully!',
    'account.save_error': 'Save failed, please try again',
    'account.back': 'Back to Home',
    'account.not_logged_in': 'Please log in to view account settings',
    'account.bookmarks_empty': 'No bookmarked species yet',
    'account.bookmarks_empty_hint': 'Tap the heart icon on a species card to bookmark it',
    'account.remove_bookmark': 'Remove Bookmark',
    'account.header_link': 'Account',
    'account.profile_info': 'Account Info',
    'account.inat_info': 'iNaturalist Integration',
    'account.inat_username': 'iNaturalist Username',
    'account.inat_username_placeholder': 'Enter your iNaturalist username',
    'account.inat_usage_consent': 'I agree to allow this site to use my "All Rights Reserved" photos',
    'account.inat_usage_hint': 'When enabled, this site will be able to display your iNaturalist photos in the gallery, cards, and tooltips, even if they are set to "All Rights Reserved" on iNaturalist.',
    'nav.privacy': 'Privacy Policy',
    'nav.terms': 'Terms of Service',
    'footer.resources': 'Resources',
    'footer.community': 'Community',
    'footer.legal': 'Legal',
    'footer.mission': 'HKBC is dedicated to documenting and protecting Hong Kong\'s rich biodiversity, providing authoritative natural data for the public, researchers, and policymakers.',
    'footer.contribution': 'Contribution',
    'footer.inat_link': 'iNaturalist HK Project',
    'footer.all_rights': 'All Rights Reserved © 2024 HK Biodiversity Collective (HKBC)',
    'loading.message': 'Loading species from the database...',
    'loading.searching': 'Exploring natural databases, please wait...',
    'dropdown.reset': 'Reset',
    'dropdown.apply': 'Apply',
    'dropdown.apply_selection': 'Apply Selection',
    'dropdown.no_results': 'No matching categories found',
    'dropdown.clear_search': 'Clear Search',
    'gallery.set_profile_error': 'Update failed',
    'gallery.set_profile_success': 'Set Success',
    'gallery.current_profile': 'Cover Photo',
    'gallery.set_profile_picture': 'Set as Cover',
    // Admin Management
    'nav.manage': 'Manage',
    'admin.title': 'Management',
    'admin.taxa_manager': 'Taxa Manager',
    'admin.taxa_fauna': 'Fauna Taxonomy',
    'admin.taxa_flora': 'Flora Taxonomy',
    'admin.species_fauna': 'Fauna Species',
    'admin.species_flora': 'Flora Species',
    'admin.taxonomy_manager': 'Taxonomy Mappings',
    'admin.users_manager': 'Users Manager',
    'admin.last_online': 'Last Online',
    'admin.joined_at': 'Joined At',
    'admin.inat_username': 'iNat Username',
    'admin.consent': 'Consent',
    'admin.role': 'Role',
    'admin.actions': 'Actions',
    'admin.change_role': 'Change Role',
    'admin.remove_user': 'Remove User',
    'admin.confirm_remove_title': 'Change User Status?',
    'admin.confirm_remove': 'Are you sure you want to change this user status? Blocked users will lose access.',
    'admin.status_active': 'Active',
    'admin.status_blocked': 'Blocked',
    'admin.taxa_group': 'Taxa Group',
    'admin.rank': 'Rank',
    'admin.taxa_type': 'Type',
    'admin.name_eng': 'English Name',
    'admin.name_chi': 'Chinese Name',
    'admin.scientific_name': 'Scientific Name',
    'admin.search_taxonomy': 'Search taxonomy names...',
    'admin.species_manager': 'Fauna Species Management',
    'admin.taxa_id': 'Taxa ID',
    'admin.informal_group_eng': 'Informal Group',
    'admin.category_eng': 'Category',
    'admin.showing': 'Showing {start} to {end} of {total}',
    'admin.total_ratio': 'Total: {filtered} / {total}',
    'admin.clear_all': 'Clear All',
    'admin.common_name_eng': 'Common Name (Eng)',
    'admin.common_name_chi': 'Common Name (Chi)',
    'admin.class_eng': 'Class',
    'admin.order_eng': 'Order',
    'admin.family_eng': 'Family',
    'admin.genus_eng': 'Genus',
    'admin.species_eng': 'Species',
    'admin.status': 'Status',
    'admin.edit_hint': 'Click text to edit inline',
    'common.confirm': 'Confirm Change',
    'common.cancel': 'Cancel',
    'admin.no_users': 'No users found',
    'admin.search_placeholder': 'Search username or iNat...',
    // Home
    'home.slogan': 'Into the Wild, onto the Cloud: Documenting Nature Together.',
    'home.discover_hk': 'Discover Hong Kong\'s Nature',
    'home.hero_title_part1': 'Exploring',
    'home.hero_title_part2': 'Biodiversity',
    'home.hero_title_part3': 'of Hong Kong',
    'home.stats_title_part1': 'Richness of',
    'home.stats_title_part2': 'Species',
    'home.stats_desc': 'Our database currently records over {total} species in Hong Kong, including {fauna} fauna and {flora} flora species.',
    'home.total_taxa': 'Total Taxa',
    'home.flora': 'Flora',
    'home.fauna': 'Fauna',
    'home.news_announcement': 'Announcements',
    'home.news_new_species': 'New Species',
    'home.view_more': 'View More',
    'home.enter_database': 'Enter Database',
    'home.added_species': 'New Species: ',
    'home.leaderboard_title': 'Contributor Leaderboard',
    'home.top_contributors': 'Top Contributors',
    'home.score': 'Score',
    'home.view_full_leaderboard': 'View Full Leaderboard',
    'home.community_discussion': 'Community Discussion',
    'home.community_feed': 'Community Feed',
    'home.go_to_discussion': 'Join Discussion',
    'home.no_comments': 'No comments yet, be the first to start a conversation!',
    // Taxa Groups
    'taxa.Birds': 'Birds',
    'taxa.Butterflies': 'Butterflies',
    'taxa.Odonates': 'Odonates',
    'taxa.Reptiles': 'Reptiles',
    'taxa.Amphibians': 'Amphibians',
    'taxa.Fish': 'Fish',
    'taxa.Mammals': 'Mammals',
    'taxa.Ants': 'Ants',
    'taxa.Beetles': 'Beetles',
    'taxa.Plants': 'Plants',
    'taxa.Flora': 'Flora',
    'taxa.Freshwater Fish': 'Freshwater Fish',
    'taxa.Marine Fish': 'Marine Fish'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('zh');

  useEffect(() => {
    const savedLang = localStorage.getItem('hkbc-lang') as Language;
    if (savedLang && (savedLang === 'zh' || savedLang === 'en')) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('hkbc-lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
