-- ============================================================
-- Migration: 20260903_create_fungi_species_and_demo.sql
-- Description: 建立真菌 (Fungi) 物種資料表、索引、RLS 權限、統計 RPC 與 5 筆 Demo 資料
-- ============================================================

-- 1. 建立 fungi_species 資料表
CREATE TABLE IF NOT EXISTS public.fungi_species (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxa_id text UNIQUE NOT NULL,
    inat_id bigint,
    col_usage_id text,
    taxa_group text DEFAULT 'FUNGI',
    
    -- 名稱資訊
    common_name_chi text,
    common_name_eng text,
    scientific_name text NOT NULL,
    alias_common_name_chi text,
    alias_common_name_eng text,
    alias_scientific_name text,
    author text,
    
    -- 分類學資訊 (Taxonomy)
    phylum_eng text,
    class_eng text,
    order_eng text,
    family_eng text,
    genus_eng text,
    species_eng text,
    sub_species_eng text,
    informal_group_eng text,
    
    -- 保育與分佈狀態
    iucn text DEFAULT 'NE',
    endemic text,
    native_status text DEFAULT 'Native',
    restrictedness text,
    
    -- 生境與特徵描述
    description_chi text,
    description_eng text,
    habitat_chi text,
    habitat_eng text,
    microhabitat_chi text,
    microhabitat_eng text,
    host_plants_chi text,
    host_plants_eng text,
    introduction_chi text,
    introduction_eng text,
    hk_distribution_chi text,
    hk_distribution_eng text,
    global_distribution_chi text,
    global_distribution_eng text,
    remarks_chi text,
    remarks_eng text,
    
    -- 圖片與關聯
    profile_picture text,
    similar_species text,
    reference_codes text,
    
    -- 系統欄位
    created_at timestamptz DEFAULT now()
);

-- 2. 建立常用查詢索引以最佳化搜尋效能
CREATE INDEX IF NOT EXISTS idx_fungi_species_taxa_id ON public.fungi_species(taxa_id);
CREATE INDEX IF NOT EXISTS idx_fungi_species_inat_id ON public.fungi_species(inat_id);
CREATE INDEX IF NOT EXISTS idx_fungi_species_scientific_name ON public.fungi_species(scientific_name);
CREATE INDEX IF NOT EXISTS idx_fungi_species_common_name_chi ON public.fungi_species(common_name_chi);
CREATE INDEX IF NOT EXISTS idx_fungi_species_common_name_eng ON public.fungi_species(common_name_eng);
CREATE INDEX IF NOT EXISTS idx_fungi_species_phylum_eng ON public.fungi_species(phylum_eng);
CREATE INDEX IF NOT EXISTS idx_fungi_species_class_eng ON public.fungi_species(class_eng);
CREATE INDEX IF NOT EXISTS idx_fungi_species_order_eng ON public.fungi_species(order_eng);
CREATE INDEX IF NOT EXISTS idx_fungi_species_family_eng ON public.fungi_species(family_eng);
CREATE INDEX IF NOT EXISTS idx_fungi_species_genus_eng ON public.fungi_species(genus_eng);
CREATE INDEX IF NOT EXISTS idx_fungi_species_informal_group_eng ON public.fungi_species(informal_group_eng);
CREATE INDEX IF NOT EXISTS idx_fungi_species_iucn ON public.fungi_species(iucn);
CREATE INDEX IF NOT EXISTS idx_fungi_species_native_status ON public.fungi_species(native_status);

-- 3. 設定 Row Level Security (RLS)
ALTER TABLE public.fungi_species ENABLE ROW LEVEL SECURITY;

-- 允許所有人 (包括未登入的匿名使用者) 讀取真菌資料
DROP POLICY IF EXISTS "Public read access for fungi_species" ON public.fungi_species;
CREATE POLICY "Public read access for fungi_species"
ON public.fungi_species FOR SELECT
TO public
USING (true);

-- 允許已登入的管理員/協作者進行新增、修改與刪除
DROP POLICY IF EXISTS "Authenticated users can manage fungi_species" ON public.fungi_species;
CREATE POLICY "Authenticated users can manage fungi_species"
ON public.fungi_species FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- 4. 建立側邊欄過濾統計 RPC 函數: get_fungi_species_stats
CREATE OR REPLACE FUNCTION public.get_fungi_species_stats(
    p_phylum_eng text[] DEFAULT '{}'::text[],
    p_class_eng text[] DEFAULT '{}'::text[],
    p_order_eng text[] DEFAULT '{}'::text[],
    p_family_eng text[] DEFAULT '{}'::text[],
    p_genus_eng text[] DEFAULT '{}'::text[],
    p_informal_group_eng text[] DEFAULT '{}'::text[],
    p_iucn text[] DEFAULT '{}'::text[],
    p_search text DEFAULT ''::text
)
RETURNS json
LANGUAGE plpgsql
AS $$
DECLARE
    result json;
BEGIN
    WITH filtered_fungi AS (
        SELECT *
        FROM public.fungi_species
        WHERE 
            (cardinality(p_phylum_eng) = 0 OR phylum_eng = ANY(p_phylum_eng)) AND
            (cardinality(p_class_eng) = 0 OR class_eng = ANY(p_class_eng)) AND
            (cardinality(p_order_eng) = 0 OR order_eng = ANY(p_order_eng)) AND
            (cardinality(p_family_eng) = 0 OR family_eng = ANY(p_family_eng)) AND
            (cardinality(p_genus_eng) = 0 OR genus_eng = ANY(p_genus_eng)) AND
            (cardinality(p_informal_group_eng) = 0 OR informal_group_eng = ANY(p_informal_group_eng)) AND
            (cardinality(p_iucn) = 0 OR iucn = ANY(p_iucn)) AND
            (p_search = '' OR 
                scientific_name ILIKE '%' || p_search || '%' OR 
                common_name_chi ILIKE '%' || p_search || '%' OR 
                common_name_eng ILIKE '%' || p_search || '%' OR
                alias_common_name_chi ILIKE '%' || p_search || '%' OR
                alias_common_name_eng ILIKE '%' || p_search || '%' OR
                alias_scientific_name ILIKE '%' || p_search || '%'
            )
    )
    SELECT json_build_object(
        'phylum_eng', (SELECT json_agg(t) FROM (SELECT phylum_eng as name, count(*) FROM filtered_fungi WHERE phylum_eng IS NOT NULL GROUP BY phylum_eng ORDER BY count(*) DESC) t),
        'class_eng', (SELECT json_agg(t) FROM (SELECT class_eng as name, count(*) FROM filtered_fungi WHERE class_eng IS NOT NULL GROUP BY class_eng ORDER BY count(*) DESC) t),
        'order_eng', (SELECT json_agg(t) FROM (SELECT order_eng as name, count(*) FROM filtered_fungi WHERE order_eng IS NOT NULL GROUP BY order_eng ORDER BY count(*) DESC) t),
        'family_eng', (SELECT json_agg(t) FROM (SELECT family_eng as name, count(*) FROM filtered_fungi WHERE family_eng IS NOT NULL GROUP BY family_eng ORDER BY count(*) DESC) t),
        'genus_eng', (SELECT json_agg(t) FROM (SELECT genus_eng as name, count(*) FROM filtered_fungi WHERE genus_eng IS NOT NULL GROUP BY genus_eng ORDER BY count(*) DESC) t),
        'informal_group_eng', (SELECT json_agg(t) FROM (SELECT informal_group_eng as name, count(*) FROM filtered_fungi WHERE informal_group_eng IS NOT NULL GROUP BY informal_group_eng ORDER BY count(*) DESC) t),
        'iucn', (SELECT json_object_agg(iucn, count) FROM (SELECT iucn, count(*) as count FROM filtered_fungi WHERE iucn IS NOT NULL GROUP BY iucn) t)
    ) INTO result;

    RETURN result;
END;
$$;

-- 5. 建立表格篩選中繼資料 RPC 函數: get_fungi_table_metadata
CREATE OR REPLACE FUNCTION public.get_fungi_table_metadata(
    p_search text DEFAULT ''::text,
    p_order text[] DEFAULT '{}'::text[],
    p_family text[] DEFAULT '{}'::text[],
    p_genus text[] DEFAULT '{}'::text[],
    p_scientific_name text[] DEFAULT '{}'::text[],
    p_common_name text[] DEFAULT '{}'::text[],
    p_iucn text[] DEFAULT '{}'::text[],
    p_native_status text[] DEFAULT '{}'::text[]
)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
    result jsonb;
BEGIN
    WITH filtered_data AS (
        SELECT * FROM public.fungi_species
        WHERE (p_search = '' OR 
               common_name_chi ILIKE '%'||p_search||'%' OR 
               common_name_eng ILIKE '%'||p_search||'%' OR 
               scientific_name ILIKE '%'||p_search||'%' OR
               alias_common_name_chi ILIKE '%'||p_search||'%' OR 
               alias_common_name_eng ILIKE '%'||p_search||'%' OR 
               alias_scientific_name ILIKE '%'||p_search||'%')
          AND (cardinality(p_order) = 0 OR order_eng = ANY(p_order))
          AND (cardinality(p_family) = 0 OR family_eng = ANY(p_family))
          AND (cardinality(p_genus) = 0 OR genus_eng = ANY(p_genus))
          AND (cardinality(p_scientific_name) = 0 OR scientific_name = ANY(p_scientific_name))
          AND (cardinality(p_common_name) = 0 OR common_name_chi = ANY(p_common_name))
          AND (cardinality(p_iucn) = 0 OR iucn = ANY(p_iucn))
          AND (cardinality(p_native_status) = 0 OR native_status = ANY(p_native_status))
    )
    SELECT jsonb_build_object(
        'order', (SELECT jsonb_agg(t) FROM (SELECT order_eng as name, order_eng as en, count(*)::int as count FROM filtered_data WHERE order_eng IS NOT NULL GROUP BY order_eng ORDER BY count DESC) t),
        'family', (SELECT jsonb_agg(t) FROM (SELECT family_eng as name, family_eng as en, count(*)::int as count FROM filtered_data WHERE family_eng IS NOT NULL GROUP BY family_eng ORDER BY count DESC) t),
        'genus', (SELECT jsonb_agg(t) FROM (SELECT genus_eng as name, genus_eng as en, count(*)::int as count FROM filtered_data WHERE genus_eng IS NOT NULL GROUP BY genus_eng ORDER BY count DESC) t),
        'scientific_name', (SELECT jsonb_agg(t) FROM (SELECT scientific_name as name, scientific_name as display, count(*)::int as count FROM filtered_data GROUP BY scientific_name ORDER BY count DESC) t),
        'common_name', (SELECT jsonb_agg(t) FROM (SELECT common_name_chi as name, common_name_chi as display, common_name_eng as en, count(*)::int as count FROM filtered_data WHERE common_name_chi IS NOT NULL GROUP BY common_name_chi, common_name_eng ORDER BY count DESC) t),
        'iucn', (SELECT jsonb_agg(t) FROM (SELECT iucn as name, iucn as display, count(*)::int as count FROM filtered_data WHERE iucn IS NOT NULL GROUP BY iucn ORDER BY count DESC) t),
        'native_status', (SELECT jsonb_agg(t) FROM (SELECT native_status as name, native_status as display, count(*)::int as count FROM filtered_data WHERE native_status IS NOT NULL GROUP BY native_status ORDER BY count DESC) t)
    ) INTO result;
    
    RETURN result;
END;
$$;

-- 6. 插入 5 隻香港代表性野生真菌 Demo 數據
INSERT INTO public.fungi_species (
    taxa_id, inat_id, taxa_group, 
    scientific_name, common_name_chi, common_name_eng, author,
    phylum_eng, class_eng, order_eng, family_eng, genus_eng, species_eng, informal_group_eng,
    iucn, native_status,
    description_chi, description_eng,
    habitat_chi, habitat_eng,
    hk_distribution_chi, hk_distribution_eng
) VALUES 
(
    'fungi_1', 355938, 'FUNGI',
    'Mycena chlorophos', '發光小菇', 'Ghostly Mycena', '(Berk. & M.A. Curtis) Sacc.',
    'Basidiomycota', 'Agaricomycetes', 'Agaricales', 'Mycenaceae', 'Mycena', 'chlorophos', 'Mushrooms',
    'LC', 'Native',
    '發光小菇是著名的發光真菌，生長於潮濕枯木或竹林落葉堆上。其菌蓋與菌柄在夜間黑暗環境中能發出明亮的淡綠色螢光，其發光機制來自螢光素酶反應。',
    'Mycena chlorophos is a species of bioluminescent agaric fungus. The fruit bodies emit a pale-green luminescence in the dark, most prominent when fresh.',
    '潮濕闊葉林底層枯木、竹林落葉堆。', 'Decaying logs and bamboo twigs in dense, humid subtropical forest floors.',
    '大帽山、大埔滘自然護理區。', 'Tai Mo Shan, Tai Po Kau Nature Reserve.'
),
(
    'fungi_2', 355944, 'FUNGI',
    'Ganoderma lingzhi', '赤芝', 'Lingzhi Mushroom', 'Sheng H. Wu, Y. Cao & Y.C. Dai',
    'Basidiomycota', 'Agaricomycetes', 'Polyporales', 'Ganodermataceae', 'Ganoderma', 'lingzhi', 'Bracket Fungi',
    'LC', 'Native',
    '赤芝為亞洲傳統著名藥用真菌，菌蓋半圓形或腎形，具堅硬皮殼與漆狀光澤，紅褐色至黑褐色。多生於闊葉樹基部或樹樁。',
    'Ganoderma lingzhi is a well-known bracket polypore mushroom found on the base and stumps of deciduous trees, characterized by its shiny laccate cap.',
    '闊葉林活樹基部、枯木樁。', 'Base and stumps of broadleaf trees in mixed forests.',
    '城門水塘、大埔滘、八仙嶺。', 'Shing Mun, Tai Po Kau, Pat Sin Leng.'
),
(
    'fungi_3', 207693, 'FUNGI',
    'Phallus rubicundus', '紅鬼筆', 'Devil''s Stinkhorn', '(Bosc) Fr.',
    'Basidiomycota', 'Agaricomycetes', 'Phallales', 'Phallaceae', 'Phallus', 'rubicundus', 'Stinkhorns',
    'LC', 'Native',
    '紅鬼筆子實體幼時呈蛋狀包被，成熟後破苞而出，海綿狀菌柄呈鮮艷橘紅色至血紅色，頂部具暗橄欖褐色產孢黏液，帶有特殊氣味吸引蒼蠅傳播孢子。',
    'Phallus rubicundus, commonly called devil''s stinkhorn, is recognized by its vibrant scarlet-to-orange column and foul-smelling spore slime at the tip.',
    '林下腐殖質豐富之土壤、竹林、草坪腐木旁。', 'Humus-rich soils, decaying wood chips, and bamboo thickets.',
    '嘉道理農場暨植物園、昂坪、香港動植物公園。', 'Kadoorie Farm, Ngong Ping, HK Zoological and Botanical Gardens.'
),
(
    'fungi_4', 383584, 'FUNGI',
    'Phallus multicolor', '黃裙竹蓀', 'Yellow Veiled Lady', 'Berk. & Broome',
    'Basidiomycota', 'Agaricomycetes', 'Phallales', 'Phallaceae', 'Phallus', 'multicolor', 'Stinkhorns',
    'LC', 'Native',
    '黃裙竹蓀擁有如蕾絲般華麗的亮黃色至橙黃色網狀裙裾，由菌蓋下緣垂掛而下，被譽為「真菌之花」，多生長於夏季雨後的落葉層中。',
    'Phallus multicolor, the yellow veiled lady, is renowned for its striking bright yellow to orange netted indusium (skirt) hanging down from the conical cap.',
    '夏季雨後林間落葉腐植層。', 'Leaf litter in subtropical forests following warm seasonal rains.',
    '大欖郊野公園、馬鞍山、香港島薄扶林林區。', 'Tai Lam Country Park, Ma On Shan, Pok Fu Lam forests.'
),
(
    'fungi_5', 54573, 'FUNGI',
    'Schizophyllum commune', '裂褶菌', 'Splitgill Mushroom', 'Fr.',
    'Basidiomycota', 'Agaricomycetes', 'Agaricales', 'Schizophyllaceae', 'Schizophyllum', 'commune', 'Mushrooms',
    'LC', 'Native',
    '裂褶菌為全球分佈極廣的木生真菌，菌蓋小型扇狀或貝殼狀，灰白色被絨毛，菌褶從基部向外輻射且縱向縱裂並向兩側反捲，乾旱時內捲保護擔孢子，遇水則重新展開。',
    'Schizophyllum commune is easily identified by its fan-shaped caps and split-gills that roll inward when dry to protect spores and reopen when moistened.',
    '向陽枯木、斷枝或倒木上。', 'Dead deciduous logs, fallen branches, and exposed rotting timber.',
    '香港廣泛分佈（郊野公園林道、園林步道周圍枯木）。', 'Widespread across Hong Kong woodland trails and country parks.'
)
ON CONFLICT (taxa_id) DO UPDATE SET
    inat_id = EXCLUDED.inat_id,
    scientific_name = EXCLUDED.scientific_name,
    common_name_chi = EXCLUDED.common_name_chi,
    common_name_eng = EXCLUDED.common_name_eng,
    author = EXCLUDED.author,
    phylum_eng = EXCLUDED.phylum_eng,
    class_eng = EXCLUDED.class_eng,
    order_eng = EXCLUDED.order_eng,
    family_eng = EXCLUDED.family_eng,
    genus_eng = EXCLUDED.genus_eng,
    species_eng = EXCLUDED.species_eng,
    informal_group_eng = EXCLUDED.informal_group_eng,
    iucn = EXCLUDED.iucn,
    native_status = EXCLUDED.native_status,
    description_chi = EXCLUDED.description_chi,
    description_eng = EXCLUDED.description_eng,
    habitat_chi = EXCLUDED.habitat_chi,
    habitat_eng = EXCLUDED.habitat_eng,
    hk_distribution_chi = EXCLUDED.hk_distribution_chi,
    hk_distribution_eng = EXCLUDED.hk_distribution_eng;

-- 7. 插入真菌分類中英文對照到 taxonomy_mappings 表 (taxa_type = 'fungi')
INSERT INTO public.taxonomy_mappings (taxa_type, rank, name_eng, name_chi) VALUES
    ('fungi', 'phylum', 'Basidiomycota', '擔子菌門'),
    ('fungi', 'class', 'Agaricomycetes', '傘菌綱'),
    ('fungi', 'order', 'Agaricales', '傘菌目'),
    ('fungi', 'order', 'Polyporales', '多孔菌目'),
    ('fungi', 'order', 'Phallales', '鬼筆目'),
    ('fungi', 'family', 'Mycenaceae', '小菇科'),
    ('fungi', 'family', 'Ganodermataceae', '靈芝科'),
    ('fungi', 'family', 'Phallaceae', '鬼筆科'),
    ('fungi', 'family', 'Schizophyllaceae', '裂褶菌科'),
    ('fungi', 'genus', 'Mycena', '小菇屬'),
    ('fungi', 'genus', 'Ganoderma', '靈芝屬'),
    ('fungi', 'genus', 'Phallus', '鬼筆屬'),
    ('fungi', 'genus', 'Schizophyllum', '裂褶菌屬'),
    ('fungi', 'informal_group', 'Mushrooms', '傘菌/菇菌類'),
    ('fungi', 'informal_group', 'Bracket Fungi', '多孔菌/木生菌類'),
    ('fungi', 'informal_group', 'Stinkhorns', '鬼筆菌類')
ON CONFLICT DO NOTHING;
